// Templates — exact ids must match src/engine/templates.js
export const TEMPLATES = [
  // Text
  { id: 'particle-field',      name: 'Particle Field',      category: 'text',     description: 'Glyph pixels orbit as animated particles' },
  { id: 'scatter-reform',      name: 'Scatter & Reform',    category: 'text',     description: 'Letters explode then snap back into place' },
  { id: 'outline-flow',        name: 'Outline Flow',        category: 'text',     description: 'Edge particles trace letterform outlines' },
  { id: 'per-char-blur',       name: 'Blur Pulse',          category: 'text',     description: 'Each character pulses in and out of focus' },
  { id: 'flip-3d',             name: 'Flip 3D',             category: 'text',     description: 'Characters flip on their Y axis' },
  { id: 'neon-trace',          name: 'Neon Trace',          category: 'text',     description: 'Neon light traces letterform edges' },
  { id: 'wave-morph',          name: 'Wave Morph',          category: 'text',     description: 'Text surface ripples like water' },
  { id: 'gravity-fall',        name: 'Gravity Fall',        category: 'text',     description: 'Glyph pixels drop under gravity then reform' },
  { id: 'typewriter',          name: 'Typewriter',          category: 'text',     description: 'Characters type in one by one' },
  { id: 'char-orbit',          name: 'Char Orbit',          category: 'text',     description: 'Each character orbits its own axis' },
  { id: 'shatter',             name: 'Shatter',             category: 'text',     description: 'Letters shatter into fragments and reform' },
  { id: 'tubing-text',         name: 'Tubing Text',         category: 'text',     description: 'Letterform edges as rotating 3D neon tubes' },
  { id: 'dot-matrix',          name: 'Dot Matrix',          category: 'text',     description: 'Pulsing LED dot-matrix display' },
  { id: 'neon-wireframe',      name: 'Neon Wireframe',      category: 'text',     description: 'Glowing wireframe edges with CRT scanlines' },
  { id: 'pixel-rain',          name: 'Pixel Rain',          category: 'text',     description: 'Glyph pixels fall like rain with trails' },
  // Geometry
  { id: 'aurora-wave',         name: 'Aurora Wave',         category: 'geometry', description: 'Flowing aurora borealis ribbons' },
  { id: 'voronoi-field',       name: 'Voronoi Field',       category: 'geometry', description: 'Animated Voronoi cell pattern' },
  { id: 'flow-field',          name: 'Flow Field',          category: 'geometry', description: 'Particles following a noise flow field' },
  { id: 'kaleidoscope',        name: 'Kaleidoscope',        category: 'geometry', description: 'Symmetrical mirrored geometry' },
  { id: 'concentric-pulse',    name: 'Concentric Pulse',    category: 'geometry', description: 'Expanding concentric rings' },
  { id: 'fractal-noise',       name: 'Fractal Noise',       category: 'geometry', description: 'Animated fractal noise texture' },
  { id: 'truchet-tiles',       name: 'Truchet Tiles',       category: 'geometry', description: 'Animated Truchet tile pattern' },
  { id: 'ascii-grid',          name: 'ASCII Grid',          category: 'geometry', description: 'Canvas-filling animated ASCII character grid' },
  { id: 'halftone',            name: 'Halftone',            category: 'geometry', description: 'Animated halftone dot pattern' },
  // Audio-reactive (will use fallback visuals when no audio loaded)
  { id: 'frequency-bars',      name: 'Frequency Bars',      category: 'audio',    description: 'FFT frequency bar visualizer' },
  { id: 'oscilloscope',        name: 'Oscilloscope',        category: 'audio',    description: 'Waveform oscilloscope display' },
  { id: 'bass-pulse-text',     name: 'Bass Pulse Text',     category: 'audio',    description: 'Text pulses and glows on bass hits' },
  { id: 'frequency-rings',     name: 'Frequency Rings',     category: 'audio',    description: 'Concentric rings driven by frequency bands' },
  { id: 'waveform-typography', name: 'Waveform Typography', category: 'audio',    description: 'Text morphs along the audio waveform' },
];

export const PALETTES = [
  { id: 'cyberpunk',  name: 'Cyberpunk'  },
  { id: 'bauhaus',    name: 'Bauhaus'    },
  { id: 'mondrian',   name: 'Mondrian'   },
  { id: 'warhol',     name: 'Warhol'     },
  { id: 'matisse',    name: 'Matisse'    },
  { id: 'hokusai',    name: 'Hokusai'    },
  { id: 'klimt',      name: 'Klimt'      },
  { id: 'vangogh',    name: 'Van Gogh'   },
  { id: 'rothko',     name: 'Rothko'     },
  { id: 'retro',      name: 'Retro'      },
  { id: 'aurora',     name: 'Aurora'     },
  { id: 'desert',     name: 'Desert'     },
  { id: 'jungle',     name: 'Jungle'     },
  { id: 'coral',      name: 'Coral'      },
  { id: 'lavender',   name: 'Lavender'   },
  { id: 'autumn',     name: 'Autumn'     },
  { id: 'spring',     name: 'Spring'     },
  { id: 'storm',      name: 'Storm'      },
  { id: 'vaporwave',  name: 'Vaporwave'  },
  { id: 'monochrome', name: 'Monochrome' },
];
